### ISSUE TITLE
Download binary from custom mirror, e.g. S3

### ISSUE THREAD

**Issue by n1ru4l** [microlinkhq/youtube-dl-exec#1]
Currently, it seems like the binary can only be downloaded from S3. I created https://github.com/przemyslawpluta/node-youtube-dl/pull/351 on node-youtube-dl

Since this package supersedes `node-youtube-dl` I think there should be an option for a custom mirror.

A possible implementation could use the `YOUTUBE_DL_DIRECT_BINARY_DOWNLOAD_URL` environment variable:

**YOUTUBE_DL_DIRECT_BINARY_DOWNLOAD_URL** - download the youtube-dl binary from the given download url, completely ignoring the `** YOUTUBE_DL_HOST**` option, while performing no lookup for retrieving the latest version of the binary. This is useful if you are hosting the youtube-dl binary on your own S3 bucket. The platform-specific extension will be appended.
E.g. the value `https://xxxxx.s3.xxxxxx.amazonaws.com/2020.11.12-youtube-dl` will result in downloading `https://xxxxx.s3.xxxxxx.amazonaws.com/2020.11.12-youtube-dl.exe` on windows.

**Comment by Kikobeats** [comment]
Hello, can you give me a valid S3 URL for testing? 🙂

**Comment by n1ru4l** [comment]
@Kikobeats Here you go :) `https://youtube-dl-mirror.s3.eu-central-1.amazonaws.com/2020.11.12-youtube-dl`, `https://youtube-dl-mirror.s3.eu-central-1.amazonaws.com/2020.11.12-youtube-dl.exe`

**Comment by Kikobeats** [comment]
shipped at `youtube-dl-exec@1.1.0`, can you confirm to me it works as you expected?

just you need to setup `YOUTUBE_DL_HOST` environment variable:

```
YOUTUBE_DL_HOST=https://youtube-dl-mirror.s3.eu-central-1.amazonaws.com/2020.11.12-youtube-dl
```

or

```
YOUTUBE_DL_HOST=https://youtube-dl-mirror.s3.eu-central-1.amazonaws.com/2020.11.12-youtube-dl.exe
```

**Comment by n1ru4l** [comment]
why cant we just appen .exe based on the detected os?

**Comment by Kikobeats** [comment]
it auto detects the platform

https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/constants.js#L16
