### ISSUE TITLE
Wrong path to youtube-dl.exe. Module uses caller's scope instead of the module's scope.

### ISSUE THREAD

**Issue by AspireOne** [microlinkhq/youtube-dl-exec#103]
in **src/constants.js**, the module uses `__dirname`, which is relative to the CALLER, not to the module. That's why it cannot resolve **"../bin/youtube-dl.exe"** - because it's **"{the calling file's path}../bin/youtube-dl.exe"**.

This behavior occurs to me when using Netlify functions.

**Comment by Kikobeats** [comment]
I'm not sure what's the issue. Can you make a PR?

**Comment by AspireOne** [comment]
I cant make a PR because I dont know whats the solution.

The path youtube-dl-exec uses to access the binary youtube-dl.exe is "**__dirame/../bin/youtube-dl.exe**", defined in "**src/constants.js**". You can define your own path in creation arguments but this is the default behavior. Do we agree on that?

Now it throws an error for me when I run it in netlify functions, because "**__dirname**" is resolved as the directory of the script that I called youtube-dl-exec from. E.g. if I call youtube-dl-exec from "**netlify/functions/download-video.js**", youtube-dl-exec resolves __dirname as "**netlify/functions**". So youtube-dl-exec uses the path "**netlify/functions/../bin/youtube-dl.exe**" to access the binary file youtube-dl.exe, which is wrong.

I dont know why this is happening. [Per the documentation](https://nodejs.org/api/modules.html#modules_dirname), __dirname should always resolve to the folder of the module, not the script that called it. But here we are.

**Comment by Kikobeats** [comment]
Sorry, I really don't know since I never used Netlify Functions.

It looks like a problem related with Netlify rather than the library itself.

I will be happy to accept a PR to improve the setup 🙂
