### ISSUE TITLE
Is the YoutubeDL exec updated when running youtubedl() function or when importing youtube-dl-exec

### ISSUE THREAD

**Issue by Joshua-Noakes1** [microlinkhq/youtube-dl-exec#106]
Title explains it all but is there a seperate function to update the youtubeDL exec. Does it happen everytime the youtubedl() function is called or does it happen when youtube-dl-exec is imported.

**Comment by Kikobeats** [comment]
Hello,

The library has a postinstall script. It's called every time you perform a `npm install` and `youtube-dl-exec` is declared as dependency or devDependency.

The postinstall script will download the latest binary version available 🙂
