### ISSUE TITLE
Getting error while installing youtube-dl-exec package.

### ISSUE THREAD

**Issue by janakparmar9491** [microlinkhq/youtube-dl-exec#107]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl-exec@2.1.0 preinstall: `npx bin-version-check-cli python ">=2"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl-exec@2.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\janak\AppData\Roaming\npm-cache\_logs\2022-07-12T13_04_36_911Z-debug.log``

**Comment by janakparmar9491** [comment]
Which node version is required to install latest version youtube-dl-exec package?

**Comment by janakparmar9491** [comment]
Hi @Kikobeats I have both installed in my system still I am getting this error.

**Comment by renandecarlo** [comment]
@Kikobeats yt-dlp is ditching python2 in the next release. It might be a good idea to update this requirement for python3
https://github.com/yt-dlp/yt-dlp/releases/tag/2022.06.29

**Comment by Kikobeats** [comment]
@renandecarlo thanks for notifying, I created a PR for that: https://github.com/microlinkhq/youtube-dl-exec/pull/109

Also, added a note about how python should be exposed, hope that helps with your problem @janakparmar9491

**Comment by janakparmar9491** [comment]
Thank you @renandecarlo and Thank you @Kikobeats .
The above error is not related to Python because in my system Python 3 was already installed.
I have resolve this error. It related to Node version I was using **Node 12** . After installing **Node 14** this error get resolved.
We should use **Node 14 and above** to use this package.

**Comment by Kikobeats** [comment]
done https://github.com/microlinkhq/youtube-dl-exec/commit/c8595bcaf4b68ef74c7c5ed8a7f385e4bdbe0435
