### ISSUE TITLE
[Bug or Misunderstanding] Attempting to JSON dump to file saves object to text instead

### ISSUE THREAD

**Issue by UserMust8** [microlinkhq/youtube-dl-exec#11]
I have this snippet of code here

```js
const youtubedl = require('youtube-dl-exec')
const fs = require('fs');


async function downloadVid(urlString) {

    const resp = await youtubedl('https://www.youtube.com/watch?v=dQw4w9WgXcQ', {dumpJson: true})

    console.log(await resp)

    fs.writeFile('helloworld.txt', (await resp).toString(), function (err) {
        if (err) return console.log(err);
        console.log('Hello World > helloworld.txt');
      });


}

downloadVid()
```

My goal is to:
1. Write the JSON dump to a file instead of just making it appear in the console
2. Download the mp4 file

The code here only outputs the JSON dump to the console but does not save it. In fact, it just saves "[Object object]" to the file. It also does not download the the video. I have to remove the parameters to make it do that.

Is this a bug or a misunderstanding on my end

**Comment by Kikobeats** [comment]
Hey, try this instead:

```bash
const youtubedl = require('.')
const fs = require('fs').promises

async function downloadVid (url, filename) {
  const output = await youtubedl(url, { dumpJson: true })
  await fs.writeFile(filename, JSON.stringify(output, null, 2))
  console.log(`Saved at: ${filename}`)
}

downloadVid('https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'output.json')
```

🙂

**Comment by UserMust8** [comment]
Hi! This snippet of code did save the JSON but it did not download the video file. Also if I wanted to switch this out for downloading thumbnails, would the process be the same or how would it work?

**Comment by Kikobeats** [comment]
try to play with https://github.com/ytdl-org/youtube-dl as CLI, you can replicate the same behavior using this library and Node.js
