### ISSUE TITLE
[Question] URL for download

### ISSUE THREAD

**Issue by A-Beille** [microlinkhq/youtube-dl-exec#111]
Hello,
I wanted to know what URL can be used in the api, like can I use a youtu.be url instead of youtube.com/watch?v=. Also, can your api only download videos from YouTube, or can it download from other videos hosting services (like TikTok for example)

Thanks you !

**Comment by Kikobeats** [comment]
yea, `youtube-dl` supports a lot of providers. Just pass the URL to the library 🙂
