### ISSUE TITLE
TypeError: `binary` and `semverRange` arguments required

### ISSUE THREAD

**Issue by Taelyn** [microlinkhq/youtube-dl-exec#112]
Continues errors

npm ERR! code 1
npm ERR! path C:\Windows\system32\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c xxxx\AppData\Local\Temp\preinstall-0a806981.cmd
npm ERR! TypeError: `binary` and `semverRange` arguments required
npm ERR!     at binaryVersionCheck (file:///xxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:7:9)
npm ERR!     at file:///xxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check-cli/cli.js:28:1
npm ERR!     at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
npm ERR!     at async Promise.all (index 0)
npm ERR!     at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
npm ERR!     at async loadESM (node:internal/process/esm_loader:85:5)
npm ERR!     at async handleMainPromise (node:internal/modules/run_main:61:12)

npm ERR! A complete log of this run can be found in:

any idea how to fix this?

**Comment by Kikobeats** [comment]
If you run. `npx bin-version-check-cli python3 \">=3.7\" what happens?

**Comment by Taelyn** [comment]
![2022-07-17 22_30_01-Remote Desktop Manager  DPC Server](https://user-images.githubusercontent.com/38536376/179421845-74ae9aab-05c5-4c06-bd76-666dcf24e917.jpg)

When i use npx bin-version-check-cli python3 3.7
Then it works

**Comment by Kikobeats** [comment]
If you are sure python is installed, try to install with `--ignore-scripts` flag:

```
npm install --ignore-scripts
```
