### ISSUE TITLE
Error youtube-dl-exec

### ISSUE THREAD

**Issue by maradona4** [microlinkhq/youtube-dl-exec#115]
How Fixed

node install
![node](https://user-images.githubusercontent.com/44541791/179899445-7c18901d-b625-46b9-ac4d-a9af4e7c37e2.png)

Python
![python](https://user-images.githubusercontent.com/44541791/179899488-85eae6fa-a86a-4f79-8562-e552a79a55ff.png)

**Comment by Kikobeats** [comment]
Hello, that's expected

> Also, it requires Python 3.7 or above available in your system as `python3`. Otherwise, the library will throw an error.
