### ISSUE TITLE
youtube-dl-exec take a lot of time to gather json data

### ISSUE THREAD

**Issue by GamerMine** [microlinkhq/youtube-dl-exec#119]
Hello,
For a long time now, I have a problem about youtube-dl-exec taking a lot of time when requesting json only and skipping download.
It take approximately 4 seconds to get the json.
When I try the same command with just yt-dlp itself, it only take 1.5 seconds. (which is already a lot for this kind of information).

Maybe something it adding 3 more seconds in youtube-dl-exec ?

EDIT: I'm running with the latest version of youtube-dl-exec (2.1.5)

Thank you
Maxime

**Comment by Kikobeats** [comment]
Hello, what command are you running?

Can you isolate that behavior into a script to make it reproducible?

**Comment by GamerMine** [comment]
Thank you for the response !

Here is what I am doing in the code :
```javascript
const youtubedl = require('youtube-dl-exec');

const before = Date.now();

youtubedl(<link>, {
        printJson: true,
        skipDownload: true
    }).then(async output => {
        console.log("youtube-dl-exec took : " + (Date.now() - before) + "ms");
    });
```
It output approximately 4000ms.

Here the command I run in my terminal (I am using the yt-dlp downloaded by youtube-dl-exec) :
`time ./yt-dlp --skip-download --print-json <link>`
It output approximately 1600ms

PS: I am replacing the <link> with an actual youtube link.

Thank you
Maxime

**Comment by Kikobeats** [comment]
Can you test this script?

```js
'use strict'

const youtubedl = require('youtube-dl-exec')

const timestamp = Date.now()

youtubedl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
  dumpSingleJson: true,
  noCheckCertificates: true,
  noWarnings: true,
  preferFreeFormats: true,
  printJson: true,
  addHeader: ['referer:youtube.com', 'user-agent:googlebot']
}).then(output => {
  // console.log(output)
  console.log(`${Date.now() - timestamp}ms`)
})
```

It's working fine to me:

![CleanShot 2022-08-10 at 16 42 33@2x](https://user-images.githubusercontent.com/2096101/183930792-52836fec-893b-4ed6-9a0a-849a77e11164.png)

**Comment by GamerMine** [comment]
Hello!

I don't know what option is making the thing faster but I added all your suggested options apart from 'dumpSingleJson:true' and it is now working how to should.
I am using NodeJS version 18.7.0 (the lastest version).

Thank you very much !
Maxime
