### ISSUE TITLE
-f option is not being formatted correctly

### ISSUE THREAD

**Issue by foxscore** [microlinkhq/youtube-dl-exec#12]
## Issue
When using the -f (format) option, youtube-dl-exec's converter puts a `=` between -f and the value, instead of a space.

For example: `youtubedl(link, { g: true, f: format })`
- It will run as `youtube-dl [link] -g -f=[format]`
- It **must** run `youtube-dl [link] -g -f [format]` to work.

Other options may also suffer from this problem, but I don't really have time to experiment right now (sorry).

## Stacktrace
> Error: Command failed with exit code 1: /root/yt2s.hub/node_modules/youtube-dl-exec/bin/youtube-dl https://youtube.com/watch?v=dQw4w9WgXcQ-g -f=140 ERROR: requested format not available at makeError (/root/yt2s.hub/node_modules/execa/lib/error.js:59:11) at handlePromise (/root/yt2s.hub/node_modules/execa/index.js:114:26) at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by Kikobeats** [comment]
according to `youtube-dl --help`:

>     -f, --format FORMAT                  Video format code, see the "FORMAT SELECTION" for all the info

so I need so clarification there since the error is right: `104` is not a format.

what's the youtube-dl command you want to run?

**Comment by foxscore** [comment]
> so I need so clarification there since the error is right: `104` is not a format.

**140**  is a format, just on a different video.
The video I used was [rmhprK9fJiw](https://www.youtube.com/watch?v=rmhprK9fJiw)

**Comment by Kikobeats** [comment]
I'm still getting the error using `youtube-dl` CLI

```bash
❯ ./bin/youtube-dl https://youtube.com/watch\?v\=dQw4w9WgXcQ-g -f=140
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading player 82e684c7
ERROR: requested format not available
```

**Comment by Kikobeats** [comment]
(accidentally closed)

**Comment by foxscore** [comment]
Exactly. My point was that there can't be an = sign. There has to be a space in between.

**Comment by Kikobeats** [comment]
hmmm maybe just use `format` instead of `f`?

```bash
❯ ./bin/youtube-dl https://youtube.com/watch\?v\=dQw4w9WgXcQ-g --format=140
[youtube] dQw4w9WgXcQ: Downloading webpage
[download] Destination: Rick Astley - Never Gonna Give You Up (Video)-dQw4w9WgXcQ.m4a
[download] 100% of 3.27MiB in 00:00
[ffmpeg] Correcting container in "Rick Astley - Never Gonna Give You Up (Video)-dQw4w9WgXcQ.m4a"

~/Projects/microlink/youtube-dl-exec master*
❯ npx ava test/args.js

~/Projects/microlink/youtube-dl-exec master*
❯ ./bin/youtube-dl https://youtube.com/watch\?v\=dQw4w9WgXcQ-g -f 140
[youtube] dQw4w9WgXcQ: Downloading webpage
[download] Rick Astley - Never Gonna Give You Up (Video)-dQw4w9WgXcQ.m4a has already been downloaded
[download] 100% of 3.27MiB
[ffmpeg] Correcting container in "Rick Astley - Never Gonna Give You Up (Video)-dQw4w9WgXcQ.m4a"
```

**Comment by foxscore** [comment]
> hmmm maybe just use `format` instead of `f`?

While this is a solution, it doesn't solve the inherit problem.

**Comment by Kikobeats** [comment]
I'm not too interested in resolving that specific thing if a simple workaround like using the verbose version of the same command resolves the thing:

```js
youtubedl('https://youtube.com/watch\?v\=dQw4w9WgXcQ-g', { 
  getUrl: true, 
  format: 140 
})
```

In fact, the code related to the arguments parsing is pretty minimal 

https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.js#L8

PRs are welcome for that!
