### ISSUE TITLE
Error: Couldn't find version of `python3`

### ISSUE THREAD

**Issue by Arnob17** [microlinkhq/youtube-dl-exec#121]
npm ERR! code 1
npm ERR! path C:\Users\pc\Desktop\Ai Bot\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python3 "> =3.7"
npm ERR! Error: Couldn't find version of `python3`
npm ERR!     at binaryVersion (file:///C:/Users/pc/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users/pc/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Local\npm-cache\_logs\2022-09-04T14_16_38_129Z-debug-0.log

**Comment by Kikobeats** [comment]
install it!

**Comment by Arnob17** [comment]
python is available in my system, I am using 3.9.4
