### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by guptaji-13** [microlinkhq/youtube-dl-exec#122]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl-exec@2.1.5 preinstall: `npx bin-version-check-cli python3 "> =3.7"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl-exec@2.1.5 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/69349405/191034098-16d8b46a-2cc7-4002-b219-53b475bb1bc0.png">

**Comment by Kikobeats** [comment]
Pretty strange. Try with `npm install --ignore-scripts=false`.

**Comment by arces** [comment]
Hmm not sure if that console is on windows or not. If it is @guptaji-13 try to see if python3 is a system or user env var, not sure if it maters but it might. I was able to install it fine on windows 10 with python 3.10.5

Any more details you can give?
