### ISSUE TITLE
API in browser

### ISSUE THREAD

**Issue by A-Beille** [microlinkhq/youtube-dl-exec#124]
How can I use the api in a browser (HTML+js) ? Hope I can.

**Comment by Kikobeats** [comment]
Hello, just use [Microlink API](https://microlink.io/docs/api/getting-started/overview) with [video](https://microlink.io/docs/api/parameters/video) or [audio](https://microlink.io/docs/api/parameters/audio) :)

e.g., https://api.microlink.io/?url=https://www.youtube.com/watch?v=6xKWiCMKKJg&audio
