### ISSUE TITLE
types for `exec` don't seem to be applied properly

### ISSUE THREAD

**Issue by bentorkington** [microlinkhq/youtube-dl-exec#125]
The library supplies Typescript definitions (thanks! 😀), but the definitions don't seem to work for the exec() function. I can see it has been prototyped, but not in a way TS seems to recognise it.

```js
      // no problem, TS knows `promise` is type Promise<YtResponse>
      const promise = ytdl('http://example.com', { writeInfoJson: true });

      // TS error: Property 'exec' does not exist on type '(url: string, flags?: YtFlags | undefined, options?: Options<string> | undefined) => Promise<YtResponse>'.
      const subProcess = ytdl.exec('http://example.com', { writeInfoJson: true });
```

**Comment by bentorkington** [comment]
I'm trying to see if I can make a PR to fix this, but I'm a bit of a Typescript noob. I think? the problem is the default export is a function with properties, and the solution might involve something like [this](https://stackoverflow.com/questions/12766528/build-a-function-object-with-properties-in-typescript)

**Comment by Kikobeats** [comment]
Hum, weird. I'm not TS expert neither ☹️

**Comment by bentorkington** [comment]
I think I've got it. I had some [help here](https://stackoverflow.com/questions/74226784/return-type-of-function-properties-in-typescript-declaration/74227375#74227375)
