### ISSUE TITLE
Hello, i need help about GCR

### ISSUE THREAD

**Issue by huutai97** [microlinkhq/youtube-dl-exec#133]
I wanna destroy "gcr:vn "in payload, i has been add cookie and use download direct link video private.

 
![image](https://user-images.githubusercontent.com/90956441/211130724-639db071-065f-4e59-9d62-192e56cf664a.png)

**Comment by Kikobeats** [comment]
Sorry, no idea what grc is; can you elaborate?

Closing until we determine this is an issue related with the library.
