### ISSUE TITLE
How to do add multiple format qualIty in JSON requested_downloads 

### ISSUE THREAD

**Issue by huutai97** [microlinkhq/youtube-dl-exec#134]
![image](https://user-images.githubusercontent.com/90956441/211173225-2627872c-933d-4201-8935-c0a0ef596aee.png)
As same as title 
how to add multiple format quality 
sorry , my english f4kjng bad

**Comment by Kikobeats** [comment]
Please https://github.com/yt-dlp/yt-dlp documentation
