### ISSUE TITLE
Is there a way to print progress

### ISSUE THREAD

**Issue by kaykhan** [microlinkhq/youtube-dl-exec#135]
usually yt-dlp will print logs of its process, i dont seem to get any logs until its all complete. Is there some way to print what is happening during download

**Comment by Kikobeats** [comment]
Hello,

Since the library returns a Promise, you can combine it with a library for measuring a Promise progress.

Check this code:

```
const logger = require('progress-estimator')()
const youtubedl = require('youtube-dl-exec')

;(async () => {
  const url = 'https://www.youtube.com/watch?v=6xKWiCMKKJg'
  const promise = youtubedl(url, { dumpSingleJson: true })
  const result = await logger(promise, `Obtaining ${url}`)
  console.log(result)
})()
```

🙂

**Comment by kaykhan** [comment]
Ah i guess i should have worded my question better, i noticed that the actual yt-dlp producing more logs than what this wrapper returns and i wanted to see the progress logs of yt-dlp.

**Comment by Kikobeats** [comment]
This library is just a convenient way to execute the yt-dlp binary, so if you pass the necessary flags to log the information, you are going to see it as the same way to execute the command in your terminal.

**Comment by maple5233** [comment]
try the example in the Readme?

```ts
const subprocess = youtubeDl.exec(url, {
     // some config
})

console.log(`Running subprocess as ${subprocess.pid}`)
subprocess.stdout?.pipe(fs.createWriteStream(path.join(logDirPath, 'stdout.log')))
subprocess.stderr?.pipe(fs.createWriteStream(path.join(logDirPath, 'stderr.log')))

setTimeout(subprocess.cancel, 60 * 60 * 1000)

subprocess.on('error', (err) => {
    console.error(err)
})
subprocess.on('close', (code) => {
    console.log(`Subprocess exited with code ${code}`)
})
```
