### ISSUE TITLE
How to use `extract_info`?

### ISSUE THREAD

**Issue by janhesters** [microlinkhq/youtube-dl-exec#136]
`yt-dlp` supports a [method called `extract_info`](https://github.com/yt-dlp/yt-dlp#extracting-information).

How do you use that with this library? I couldn't find anything regarding that in the README or in any issue.

**Comment by Kikobeats** [comment]
Hello, it's not supported, but we can do it 🙂

How different is that than dump the output into a JSON? can you make comparsion?

**Comment by janhesters** [comment]
I think the main difference is that `extract_info` does not download anything.

I'm currently running with

```
simulate: true,
skipDownload: true,
```

which should also not download anything, correct?

I only care about the meta data.

**Comment by Kikobeats** [comment]
How different is that compared with the README example?

```
const youtubedl = require(https://github.com/microlinkhq/youtube-dl-exec)

youtubedl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
  dumpSingleJson: true,
  noCheckCertificates: true,
  noWarnings: true,
  preferFreeFormats: true,
  addHeader: [
    'referer:youtube.com',
    'user-agent:googlebot'
  ]

}).then(output => console.log(output))
```

It is not downloading nothing – at least from a user perspective

**Comment by Kikobeats** [comment]
Trying to simulate, but I'm not seeing any kind of difference:

```bash
$ yt-dlp 'https://www.youtube.com/watch?v=6xKWiCMKKJg' \
  --dump-single-json \
  --no-check-certificates \
  --no-warnings \
  --prefer-free-formats \
  --add-header 'referer:youtube.com' \
  --add-header 'user-agent:googlebot' \
  --simulate \
  --no-download
  ```

**Comment by Kikobeats** [comment]
Closing since I didn't note any difference
