### ISSUE TITLE
Python check disable option

### ISSUE THREAD

**Issue by origeva** [microlinkhq/youtube-dl-exec#139]
Hey! I'd appreciate having the option to disable the python binary check since I'm installing node modules as part of a build process,
where I don't need python as part of the environment.

Can you add the option to disable the python check with an env variable?

**Comment by Kikobeats** [comment]
what if you just add `python` binary as a mock?

**Comment by origeva** [comment]
Thank you for the quick reply.

I would need to create a script that returns the supported version.
It really seems like an avoidable workaround.
I'm trying to reduce the image size so avoiding downloading the bin-version-check package would be another great outcome.

**Comment by Kikobeats** [comment]
@origeva I created a PR; Can you please verify it will work at your end?

**Comment by origeva** [comment]
The build works, but on windows the variable interpretation doesn't work ("'[[' is not recognized as an internal or external command")

I really appreciate the quick response

**Comment by origeva** [comment]
Maybe create a script/preinstall.js script to handle with cross env variable interpretation?

script/preinstall.js
```
const cp = require('child_process')

// if (!process.env.YOUTUBE_DL_SKIP_PYTHON_CHECK === 'true') { // Case sensitive
if (!/^true$/i.test(process.env.YOUTUBE_DL_SKIP_PYTHON_CHECK)) { // regex for case-insensitive check (YOUTUBE_DL_SKIP_PYTHON_CHECK=tRuE)
	const { stderr, stdout } = cp.exec('npx bin-version-check-cli python3 "> =3.7" || npx bin-version-check-cli python "> =3.7"', (err) => {
		if (err) {
			throw err
		}
	})

	stderr.pipe(process.stderr)
	stdout.pipe(process.stdout)
}
```

package.json
```
"scripts": {
    ...
    "preinstall": "node scripts/preinstall.js",
    ...
}
```

**Comment by Kikobeats** [comment]
Did you try the last version? https://github.com/microlinkhq/youtube-dl-exec/releases/tag/v2.3.0 🙂

**Comment by origeva** [comment]
Aaaand it works, alright, thanks a lot!
