### ISSUE TITLE
How to gracefully stop ?

### ISSUE THREAD

**Issue by Seblor** [microlinkhq/youtube-dl-exec#14]
I am unable to find any way to gracefully stop the download. Even if I use the raw ChildProcess and kill it, the youtube-dl process is killed but it leaves the ffmpeg process hanging, locking the resulting file. And manually killing the ffmpeg process leaves the file corrupted.

**Comment by Kikobeats** [comment]
can you try to pass `SIGKILL` as `killSignal` ?

```js
const subprocess = youtubedl.raw('https://example.com', { dumpJson: true }, { killSignal: 'SIGKILL`} )
```

**Comment by Seblor** [comment]
Sadly this does not work. It still leaves the ffmpeg process hanging.

I am on windows, so maybe it is OS related ?

**Comment by Kikobeats** [comment]
ops looks like windows could be very particular

https://github.com/sindresorhus/execa/issues/433

**Comment by Seblor** [comment]
I already tried setting `windowsHide` to false, using `terminate`, but the behavior is still the same.
