### ISSUE TITLE
issues in deploying

### ISSUE THREAD

**Issue by jacktheboss220** [microlinkhq/youtube-dl-exec#142]
Hello, 

I'm deploying an app on keyob.com, there is some issue like 

![image](https://user-images.githubusercontent.com/81576386/222751214-84d51d2c-0310-4679-abf8-c8e237e17541.png)

can any one help me.

Thanks

**Comment by Kikobeats** [comment]
are you running on Windows?

**Comment by jacktheboss220** [comment]
> are you running on Windows?

it is working on local machine, but not on hosting server.

**Comment by Kikobeats** [comment]
@jacktheboss220 Can you try to install `youtube-dl-exec@2.4.0-beta.0`? it should to fix the problem

Please confirm and I can ship as stable 🙂

**Comment by jacktheboss220** [comment]
> @jacktheboss220 Can you try to install `youtube-dl-exec@2.4.0-beta.0`? it should to fix the problem
> 
> Please confirm and I can ship as stable 🙂

yes it worked 
thnx ❣️

**Comment by Kikobeats** [comment]
awesome 🎉  published `youtube-dl-exec@2.4.0`

**Comment by jacktheboss220** [comment]
thnx for the help :)
