### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by EpicJosch** [microlinkhq/youtube-dl-exec#145]
Hi. How can i do error handling when using youtubedl(url, downloadOptions)

**Comment by Kikobeats** [comment]
Hello,

The library returns a promise, so I guess it could be as simple as use a try/catch?


```js
try {
  const output = youtubedl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
    dumpSingleJson: true,
    noCheckCertificates: true,
    noWarnings: true,
    preferFreeFormats: true,
    addHeader: [
      'referer:youtube.com',
      'user-agent:googlebot'
    ]
  })
  console.log('OUTPUT:', output)
} catch(error) {
  console.error('ERROR:', error)
}
```

Note there is not download options as you mention. The options passed will be passed to [yt-dlp](https://github.com/yt-dlp/yt-dlp)
