### ISSUE TITLE
Not automatically downloading the binary

### ISSUE THREAD

**Issue by italodeandra** [microlinkhq/youtube-dl-exec#146]
I installed 2.4.0 and 2.3.1 and I'm still not getting the binary.

Does it work only on Linux? I'm on Windows.

**Comment by italodeandra** [comment]
I'm doing some investigation, and on this code:

![image](https://user-images.githubusercontent.com/19225266/231245040-06fc6a8c-9552-4e72-b8ec-22d1fb89ce7b.png)

The `content-type` is undefined and the `data` is a Buffer.

![image](https://user-images.githubusercontent.com/19225266/231245130-a13ce658-c1f2-4f64-822b-4bd4cc1a4118.png)

So `JSON.parse` won't work.

**Comment by Kikobeats** [comment]
Can you try replacing `JSON.parse(data)` to do `JSON.parse(data.toString()` instead?

**Comment by italodeandra** [comment]
I fixed locally it by doing this: `if (typeof data !== "string") return data`.

On my server it worked without changing it, so this issue might be only on Windows.

**Comment by Kikobeats** [comment]
Can you check with `youtube-dl-exec@2.4.1`? I think the issue should be fixed
