### ISSUE TITLE
youtube-dl returns an invalid JSON

### ISSUE THREAD

**Issue by ainsey11** [microlinkhq/youtube-dl-exec#15]
Hi!

Thanks for writing this - the new wrapper is far easier to use!

I seem to be hitting issues when dealing with playlists, not sure if it's down to my implementation in the code or an error with your library, hopefully you can help!

Here's a simple test function I wrote:

```js
const youtubedl = require("youtube-dl-exec")

async function Test(VideoURL){
    let result = await youtubedl(VideoURL,{
        dumpJson: true,
        noCallHome: true,
    })
    console.log(result)
}

Test("https://www.youtube.com/playlist?list=PLvgS71fU12MawZ_u2HverscJHqsB84M3z")
```

When I run this I get the following error:
```
node utils/temp.js 
(node:352052) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token { in JSON at position 37553
    at JSON.parse (<anonymous>)
    at parse (/home/robert/Documents/Personal-Code/ssvd-metafetcher/node_modules/youtube-dl-exec/src/index.js:13:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Test (/home/robert/Documents/Personal-Code/ssvd-metafetcher/utils/temp.js:4:18)
```

if I run the youtube-dl command by hand, it does return valid JSON:
```
node_modules/youtube-dl-exec/bin/youtube-dl --no-call-home --dump-json https://www.youtube.com/playlist?list=PLVJa0bdiLG6H9zOYoNEt_J-PtQFrp22wx | jq
```
(the output was huge, so I'll spare pasting it here, but jq parsed the output without any problems)

It works perfectly with a single video, so only seems to affect playlists, I've tried a few different playlist URL's and it seems an issue on all of them,

I've also tried with the noWarnings param and that made no difference.

youtube-dl binary version is: `2021.04.17` (though tried it with latest and made no difference)
youtube-dl-exec version is: `1.2.1`
node version is: `v14.16.0`
OS is: `Ubuntu 20.04`

Hopefully it's something simple!

**Comment by Kikobeats** [comment]
Hello, @ainsey11  thanks for opening this issue.

I was debugging and this is the output of your command:

https://gist.github.com/Kikobeats/421642b94a16ae017c2744b072c577da

Unfortunately, It's not a valid JSON:

```bash
❯ node
Welcome to Node.js v16.0.0.
Type ".help" for more information.
> JSON.parse(fs.readFileSync('./debug.log').toString())
Uncaught SyntaxError: Unexpected token { in JSON at position 37665
```

So the thing is `--dump-json` is generating a not valid JSON.

I think this issue should be open at https://github.com/ytdl-org/youtube-dl

**Comment by Kikobeats** [comment]
I found youtube-dl is returning a collection of objects using break like as separator, so I guess I can create the real JSON

**Comment by ainsey11** [comment]
Oh that's a good spot! the `jq` tool must be ignoring the invalid json or dealing with it internally somehow, 

I'll raise a bug with youtube-dl but if you were able to do something clever with the break that would be much appreciated!

**Comment by Kikobeats** [comment]
I thought youtube-dl is using http://ndjson.org format, so I wrote a function for parsing the result respecting the spec

```js
const ndjson = (str) => {
  const collection = str.split(/\n|\n\r/).filter(Boolean)
  return collection.map(jsonStringRow => JSON.parse(jsonStringRow))
}
```

but it's still failing. It would be really appreciated if you can open an issue on the main repo and let's see what the most affordable solution we can adopt

**Comment by ainsey11** [comment]
Thanks for having a look - I noticed it's missing a } on the end of the output too:

![image](https://user-images.githubusercontent.com/6608275/116064969-6c6b6600-a67e-11eb-9980-75e0b2111f4c.png)

I've raised a bug with them at https://github.com/ytdl-org/youtube-dl/issues/28875 but you are entirely right, the output from youtube-dl is 100% not JSON!

**Comment by ainsey11** [comment]
Just had an update on the youtube-dl issue - https://github.com/ytdl-org/youtube-dl/issues/28875#issuecomment-826782678

I tweaked my config to:

```
async function Test(VideoURL){
    let result = await youtubedl(VideoURL,{
        //dumpJson: true,
        noWarnings: true,
        noCallHome: true,
        "dump-single-json": true,
    })
    console.log(result)
}
```

and I do now get valid JSON back, it's a single json object that contains an array and a few other fields like this (not complete output, just an example):

```
{
  extractor: 'youtube:tab',
  _type: 'playlist',
  uploader: 'AvE',
  entries: [
    {
      upload_date: '20170129',
      extractor: 'youtube',
      vbr: 2366.247,
      height: 1080,
      like_count: 10026,
      },
```

so I guess I can now iterate over the objects in the entries array to get my individual video information and should be good!

might be worth noting on the readme that if dealing with playlists then you need to use `dump-single-json` instead of `dumpJson` ?

Thanks for your help with this!

**Comment by Kikobeats** [comment]
happy to see you resolved the issue!

It's the first time I see `dump-single-json`. I adopted that flag since looks like it's done the thing that before but also parsing playlist as expecting 🙂

**Comment by ainsey11** [comment]
Brilliant, thank you!

For anyone else that comes across this issue in the future, here's a snippet that grabs all video URL's from a playlist:
```
const youtubedl = require("youtube-dl-exec")

async function Test(VideoURL){
    let result = await youtubedl(VideoURL,{
        noWarnings: true,
        noCallHome: true,
        "dump-single-json": true,
    })
    //console.log(result)
    for (video of await result.entries){
        console.log(video.webpage_url)
    }
}

Test("<enter_playlist_url_here>")

```
