### ISSUE TITLE
yt-dlp warnings are treated as errors, causing a failure

### ISSUE THREAD

**Issue by miraclx** [microlinkhq/youtube-dl-exec#153]
> Small issue here, warnings also write to stderr. This means youtube-dl-exec fails anytime yt-dlp raises a warning, but not an error.

_Originally posted by @miraclx in https://github.com/microlinkhq/youtube-dl-exec/issues/137#issuecomment-1603380649_

Example

```console
➜ youtube-dl-exec/bin/yt-dlp --no-cache-dir --dump-single-json -- DN0FUrrjlEg
WARNING: [youtube] DN0FUrrjlEg: Signature extraction failed: Some formats may be missing
{"id": "DN0FUrrjlEg", "title": "AN AUTUMN FOR CRIPPL ...
```

This logic makes it so, youtube-dl-exec outrightly fails when the stderr is nonempty, which in the case of mere errors, it isn't:

https://github.com/microlinkhq/youtube-dl-exec/blob/a1e890b1cae0550499f6474e594a6533f890309e/src/index.js#L14

**Comment by miraclx** [comment]
I suppose the use of `--no-warnings` as used in the test of the patch that introduced this change works as well. But implicitly treating warnings as errors without providing any useful information as to what happened is suboptimal.

**Comment by Kikobeats** [comment]
This is by yt-dlp design, so yea, so should to pass --no-warnings 🙂

**Comment by Kikobeats** [comment]
Hum, can you promote a PR fixing this?

Otherwise --no-warnings is less optimal but explicit and predictable.

**Comment by miraclx** [comment]
I think `--no-warnings` by default might be a comfortable compromise, since according to the logic, those warnings won't be exposed to the user unless there are actual errors, I think those errors would take higher priority anyway.

If we want this behaviour to be configurable, perhaps we leverage the `opts` argument.

Read the `warnings` field, which defaults to `false`, and remove the field from the `opts` object before passing it down to `execa`.

**Comment by Kikobeats** [comment]
I prefer to don't setup default flags, that makes the library opinionated.

Since this behavior is by yt-dlp design, I feel okay with passing the flag explicitly 🙂
