### ISSUE TITLE
Incorrect Typings for return value

### ISSUE THREAD

**Issue by leumasme** [microlinkhq/youtube-dl-exec#155]
https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.d.ts#L255-L262

The return value is always typed as `YtResponse`, which is an object with various properties such as `title`.  
This is not a correct typing, as the function returns a `string` unless `printJson: true` is passed as a flag.

[Here](https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAeSmAlgewHYGc4F44DeocJcWA1ilACJoDuGANmgIYAmA-AFxwBGaaRjBYYA3MVJ0ATijAwAggFcwaAMqLe3PgKEjxIUnCgyMYAFJZMW-oOFjQAX1ChIsOACUYWRYzB5CEiSoYEI8WGAmAOb6hgDGABYiGDCMYREoGNGOzuDQ8EiomFgA6iLmlhj+RAakxhnlmDwRijDZIKBsMLGMLFLwAGaKGLGFlTAAHl3KMAA8ACpwE3IYbDgF6NgAfAAUaMgbWDxzAJRHi+PLq4j7RaWmFphwHB5ePn5pUfqgAPTfcAC0-zgiiwMCkcFiaE6AP+OSEfjA8RQWAAklh5Kp0pl-BMpnJtgQHMccr9Eci0RisZEyCxUFh+igvGQqV8QPC4GTUeiMAheAArLp+fC42LTAlGEwNDBNKQtOBEknfTkUnn8wU0ukMpmeby+fRAA) is an example of how this can be typed correctly (but maybe its possible to do it even better?).

Or you could just type it as `YtResponse | string`, which would be shorter than the above solution and also correct, although slightly less convenient to use (since library user manually has to narrow the type)

**Comment by Kikobeats** [comment]
Can you make a PR? 🙂

**Comment by vishnujee** [comment]
error /opt/render/project/src/node_modules/youtube-dl-exec: Command failed.
Exit code: 13

these error is coming at render during deployment

**Comment by Kikobeats** [comment]
I'm not a TypeScript so I don't know if the types are good enough or not; I'll be happy to accept any PR updating types 🙂
