### ISSUE TITLE
Webm to MP3 or other format

### ISSUE THREAD

**Issue by milimyname** [microlinkhq/youtube-dl-exec#156]
Hi everyone.

I thank you for the package which is super easy to use but I wonder how I can get a mp3 or other version to support the audio for the ios safari etc. 

1. The only solution comes to me which is to convert it using external services or build an microservice for it. 
2. Is there any workaround?

PS:
``` js
const output = await youtubedl(url, {
		dumpSingleJson: true,
		noCheckCertificates: true,
		noWarnings: true,
		preferFreeFormats: true,
		addHeader: ['referer:youtube.com', 'user-agent:googlebot'],
		extractAudio: true,
		audioFormat: 'mp3'
	});
```

I installed ffmpeg but it didn't work ( I could not find the url).

**Comment by Kikobeats** [comment]
`youtubedl` just get the audio from the source. In order to convert it into a different format, you should to use a specific software for that
