### ISSUE TITLE
Selected folder paths for downloads not implemented

### ISSUE THREAD

**Issue by DoormatIka** [microlinkhq/youtube-dl-exec#157]
```ts
const soundcloud = "https://soundcloud.com/spxrxt";

const res = ytdl(soundcloud, {
    retries: 3,
    paths: ??????????
});
```
I would like for this to support creating folders for different downloads. Thank you.

**Comment by Kikobeats** [comment]
Hello, this library is a wrapped of https://github.com/yt-dlp/yt-dlp, so check the help of it 🙂

**Comment by masterkain** [comment]
ok but paths definition seems missing
