### ISSUE TITLE
using best option , it not always give that url which contains both video and audio of youtube link

### ISSUE THREAD

**Issue by Streamingo-ai** [microlinkhq/youtube-dl-exec#161]
ytdlOptions = {
    dumpJson: true,
    skipDownload: true,
    noCheckCertificates: true,
    noWarnings: true,
    **format: 'bestvideo+bestaudio/best',**
    addHeader: [
      'referer:youtube.com',
      'user-agent:googlebot',
    ],
  };

i am passing above option to get that url which contains both audio and video of youtube video link. 

Any help , which options need to pass. (I am using latest version @2.4.7 )

**Comment by Kikobeats** [comment]
This library is just a wrapper around [yt-dlp](https://github.com/yt-dlp/yt-dlp)
