### ISSUE TITLE
Update / Install of 2.4.3+ fails with Node v16 due to preinstall script

### ISSUE THREAD

**Issue by JeffJassky** [microlinkhq/youtube-dl-exec#165]
### **Issue Description:**
When attempting to update the youtube-dl-exec package to versions 2.4.3 through 2.4.8 in my project using node 16.10.0, I encountered an error during the execution of the preinstall script. version 2.4.2 installs with node 16.10.0 successfully without the error.

### **Steps to Reproduce:**

1. Use node 16
2. Navigate to project directory.
3. Run npm update youtube-dl-exec.

### **Expected Result:**
The package should update without any errors.

### **Actual Result:**
Received an error related to the execution of the preinstall script:

```bash
npm i youtube-dl-exec --save
npm ERR! code 13
npm ERR! path /Users/jeffjassky/Projects/StoryFolderDesktop/node_modules/youtube-dl-exec
npm ERR! command failed
npm ERR! command sh -c node scripts/preinstall.mjs

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeffjassky/.npm/_logs/2023-09-07T17_41_03_480Z-debug.log
```
### **System Info:**
OS: macOs Monterey 12.1
Node.js version: v16.10.0
npm version: v7.24.0
Project path: /Users/jeffjassky/Projects/StoryFolderDesktop

### **Additional Notes:**
- I have tried clearing npm cache and manually updating the package, but the issue persists.
- I've checked permissions and even attempted running with elevated permissions using sudo, but to no avail.
- I'm using nvm to manage Node.js versions.

**Comment by Kikobeats** [comment]
can you run the command manually? 

```
sh -c node scripts/preinstall.mjs
```

What is it saying?

**Comment by Kikobeats** [comment]
closing since no reply

**Comment by chrisporter** [comment]
Would it be possible to reopen please? I still get this with the 2.4.14, on both Mac and Windows.

Try the command above opens the node repl.

```
Welcome to Node.js v16.13.0.
Type ".help" for more information.
> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
```

running ``node scripts/preinstall.mjs`` there is no output. 

Thanks for taking a look and please let me know if I can help.

**Comment by Kikobeats** [comment]
CI is green so pretty sure it's your local environment
https://github.com/microlinkhq/youtube-dl-exec/actions/runs/6323338918/job/17170728224#step:5:1

**Comment by chrisporter** [comment]
Thanks, it gets to the end of the ``preinstall.mjs`` without any errors so the Python is all installed.
