### ISSUE TITLE
Download Progress

### ISSUE THREAD

**Issue by jhemmmm** [microlinkhq/youtube-dl-exec#17]
Hello,

I'd like to know how to get it's download progress. The output doesn't seems to be working.
```

const youtubedl = require('youtube-dl-exec');

youtubedl('https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8', {
	noWarnings: true,
	noCheckCertificate: true,
}).then((output) => console.log(output));

```

**Comment by Kikobeats** [comment]
hello, not sure what progress means.

Can reproduce what you want using the `youtube-dl` CLI?

**Comment by jhemmmm** [comment]
An event, which returns the download progress of the file.
On the older version, I was able to get the percentage, size, status of the download progress with this sample code.

`video.on('info', (info) => {
	extract.size = info.size;
});
var downlaoded = 0;
var tempPercentage = 0;
let pos = 0;
let percentage = 0;
video.on('data', (chunk) => {
	pos += chunk.length;
	if (extract.size) percentage = ((pos / extract.size) * 100).toFixed(0);

	if (tempPercentage != percentage) {
		console.log(
			JSON.stringify({
				percentage: percentage,
				length: extract.size,
				status: 'downloading',
				error: false
			})
		);
		tempPercentage = percentage;
	}
});

video.on('end', function () {
	console.log(
		JSON.stringify({
			percentage: 100,
			length: extract.size,
			status: 'downloaded',
			error: false
		})
	);
	process.exit();
});`

**Comment by Kikobeats** [comment]
You can use the promise returned by the library in combination with
https://github.com/bvaughn/progress-estimator

This library doesn't return any kind of custom event.

**Comment by jhemmmm** [comment]
> You can use the promise returned by the library in combination with
> https://github.com/bvaughn/progress-estimator
> 
> This library doesn't return any kind of custom event.

which is really sad, it doesn't even return the total size of the file.
I was planning if, it is possible to parse the content from 
```
subprocess.stderr.on('data', function (data) {
        //parse "data", return json {size, downloaded, total, percentage}
	console.log('stderr: ' + data);
});
```

**Comment by sunshineLixun** [comment]
you can do this

```js
  const ytDownload = youtubedl.exec(your viedeo url, {
    writeAutoSub: true,
    writeSub: true,
    convertSubs: "srt",
    output: process.cwd(),
    format: "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
  });

  ytDownload.stdout?.on("data", data => {
    let output = data
      .trim()
      .split(" ")
      .filter(n => n);
    if (output[0] === "[download]" && parseFloat(output[1])) {
      console.log({
        progress: parseFloat(output[1]),
        size: output[3],
        transferred: output[5],
        estimated: output[7]
      });
    }
  });

  ytDownload.stdout?.on("end", data => {
    console.log("stdout end", data);
  });

  ytDownload.stdout?.on("close", data => {
    console.log("stdout close", data);
  });

  ytDownload.stdout?.on("end", data => {
    console.log("end", data);
  });

  ytDownload.stdout?.on("close", data => {
    console.log("close", data);
  });

  ytDownload.stdout?.on("data", data => {
    console.log("data", data);
  });
```

**Comment by sunshineLixun** [comment]
you can do this

```js
  const ytDownload = youtubedl.exec("https://www.youtube.com/watch?v=ISnxs-NlRYg", {
    writeAutoSub: true,
    writeSub: true,
    convertSubs: "srt",
    output: process.cwd() + "/resources/subtitle",
    format: "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
  });

  ytDownload.stdout?.on("data", data => {
    try {
      const buffer = Buffer.from(data, "utf-8");

      let output = buffer
        .toString()
        .trim()
        .split(" ")
        .filter(n => n);

      if (output[0] === "[download]" && parseFloat(output[1])) {
        console.log({
          progress: parseFloat(output[1]),
          size: output[4],
          speed: output[6],
          estimated: output[8]
        });
      }
    } catch (err) {
      console.log("parse error", err);
    }
  });

  ytDownload.stdout?.on("end", data => {
    console.log("stdout end", data);
  });

  ytDownload.stdout?.on("close", data => {
    console.log("close", data);
  });
```
