### ISSUE TITLE
Getting 404 Errors

### ISSUE THREAD

**Issue by BarakBinyamin** [microlinkhq/youtube-dl-exec#171]
Getting 404 error when trying to use youtube-dl-exec

updating yt-dlp to stable@2023.07.06 solved the issue

```
yt-dlp --update-to stable@2023.07.06
```

This was listed as an issue a few months ago on the yt-dlp page [https://github.com/yt-dlp/yt-dlp/issues/7811](https://github.com/yt-dlp/yt-dlp/issues/7811)

**Comment by Kikobeats** [comment]
great to know, thanks!
