### ISSUE TITLE
Unable to extract after uploading the code to a server

### ISSUE THREAD

**Issue by MarcusVJ** [microlinkhq/youtube-dl-exec#179]
Hello everyone.

I'm developing an API in NodeJS Express that feeds an Android platform that plays videos hosted on a YouTube channel where all the videos are unlisted. When running on my local machine, the workflow on that API runs without a problem, but when I try to run the same API (with the same code) in my host machine at a Virtuozzo server, the package returns the following error:

`Error: Command failed with exit code 1: /home/jelastic/ROOT/node_modules/youtube-dl-exec/bin/youtube-dl https://youtu.be/FSk9y7bsvxk --dump-single-json --no-warnings --prefer-free-formats --verbose --add-header referer:youtube.com --add-header user-agent:googlebot
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://youtu.be/FSk9y7bsvxk', u'--dump-single-json', u'--no-warnings', u'--prefer-free-formats', u'--verbose', u'--add-header', u'referer:youtube.com', u'--add-header', u'user-agent:googlebot']
[debug] Adding header from command line option referer:youtube.com
[debug] Adding header from command line option user-agent:googlebot
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-x86_64-with-centos-7.9.2009-Core
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jelastic/ROOT/node_modules/youtube-dl-exec/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jelastic/ROOT/node_modules/youtube-dl-exec/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/jelastic/ROOT/node_modules/youtube-dl-exec/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/jelastic/ROOT/node_modules/youtube-dl-exec/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/jelastic/ROOT/node_modules/youtube-dl-exec/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Here's the code so far (scuffed because it is still in development):

```
youtubedl(videoURL, {
      dumpSingleJson: true,
      noWarnings: true,
      preferFreeFormats: true,
      verbose: true,
      addHeader: ["referer:youtube.com", "user-agent:googlebot"],
    })
      .then((output) => {
        let videoFormats = {
          v1080: {
            quality: 1080,
            audio_available: "",
            audio_url: "",
            video_available: "",
            video_url: "",
          },
        };
        output.formats.forEach((metaData) => {
          //1080p video
          if (metaData.format_id === "137") {
            videoFormats.v1080.video_url = metaData.url;
            videoFormats.v1080.video_available = true;
          }
          //1080p audio
          else if (metaData.format_id === "140") {
            videoFormats.v1080.audio_url = metaData.url;
            videoFormats.v1080.audio_available = true;
          }
        });

        res.json(videoFormats);
      })
      .catch((err) => {
        res.sendStatus(502);
        utils._throw(req.url, err);
      });
```
Can someone shed some light on how to fix this?

**Comment by Kikobeats** [comment]
Hello, it isn't a problem with the library itself, so I can't help there.

You can always use Microlink API for getting the video 🙂
https://api.microlink.io/?url=https://youtu.be/FSk9y7bsvxk&video
