### ISSUE TITLE
youtubedl.exec is missing cancel() function

### ISSUE THREAD

**Issue by RobertoUa** [microlinkhq/youtube-dl-exec#181]
It looks like it is due to migration to `tinyspawn`.

Unfortunately, I can't provide the code to reproduce the stuck request. I use the tool to fetch JSON (`--dump-single-json`) from youtube and I cancel requests that are longer than 5 secs. Usually, it happens when there are many simultaneous requests and a slow network.

**Comment by Kikobeats** [comment]
without a reproduction I can't work in the darkness

Did you try to setup timeout and kill signal? In this way
https://github.com/microlinkhq/tinyspawn#extending-behavior

**Comment by RobertoUa** [comment]
>without a reproduction I can't work in the darkness

okay, here's the code to reproduce the issue

```
const proc = youtubedl.exec(url);
proc.cancel() // error!
```


Unfortunately `extend` won't work in my case. I need `cancel()`

**Comment by Kikobeats** [comment]
What I need is a reproduction of a stuck request

**Comment by RobertoUa** [comment]
it's not a stuck request (sorry, I misinformed you) it's just a long request.
I guess you can simulate slow network with some OS tools (there are for mac and linux)

**Comment by RobertoUa** [comment]
anyway, I checked `execa`, and `cancel` is just `ChildProcess.kill`

seems updating to tinyspawn introduced this breaking change

**Comment by Kikobeats** [comment]
The third parameter is for passing options against tinyspawn, so you can have the same behavior passing timeout and kill signal, in this way

```
await youtubedl.exec('https://www.youtube.com/watch?v=6xKWiCMKKJg',{
  dumpSingleJson: true
}, {
  timeout: 5000,
  killSignal: 'SIGKILL'
})
```

Does it make sense to you?

**Comment by spike11302000** [comment]
i can confirm as well that youtubedl.exec doesn't expose any of the Child Process function.

**Comment by Kikobeats** [comment]
Thanks for reporting, this is actually a bug, I filled a new issue https://github.com/microlinkhq/tinyspawn/issues/10

**Comment by Kikobeats** [comment]
- fixed tinyspawn
- upgrade the dependency
- added a [doc](https://github.com/microlinkhq/youtube-dl-exec#timeout--cancellation) section 


It should work fine now, can you confirm? <picture data-single-emoji=":pra:" title=":pra:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pra/b3935c9f40d8c090.png" alt=":pra:" align="absmiddle"></picture>

**Comment by spike11302000** [comment]
It now works now, Thank you.
