### ISSUE TITLE
tinyspawn version conflict 

### ISSUE THREAD

**Issue by JeffJassky** [microlinkhq/youtube-dl-exec#182]
# Description
By adding tinyspawn as a dependency in #173, a version conflict was introduced, effectively disabling the package for earlier versions of node.

- tinyspawn targets node engines >= 18
- youtube-dl-exec targets node engines >= 14

# Suggestion:
Ensure tinyspawns "engines" targets >=14

I have filed a pull request for this here: https://github.com/microlinkhq/tinyspawn/pull/8

**Comment by Kikobeats** [comment]
Closing since it's being addressed there, there is no necessity to duplicate the issue.

**Comment by JeffJassky** [comment]
Great! Thanks so much! It would be great if we could update this package to use the new tinyspawn version and have a new release.
