### ISSUE TITLE
This expression is not callable.

### ISSUE THREAD

**Issue by valzzu** [microlinkhq/youtube-dl-exec#183]
![image](https://github.com/microlinkhq/youtube-dl-exec/assets/52419539/c98cd667-b60c-43b8-beb2-301ad22058df)
![image](https://github.com/microlinkhq/youtube-dl-exec/assets/52419539/27575808-9121-4d58-b6a9-ba308759b353)

is this something i should be concerned about? using typescript if that's needed :)

**Comment by Kikobeats** [comment]
I'm not sure what that means.

This is the source code:
https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.js#L24

This is the type definitions:
https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.d.ts

Maybe you can try to tweak types locally to see if they fit better, appreciated if you can make a PR for improving them 🙏
