### ISSUE TITLE
Issue with Python Check

### ISSUE THREAD

**Issue by taynotfound** [microlinkhq/youtube-dl-exec#187]
So i have 2 Python versions. One invoked with `python` and one with `python3`.

I tried removing the `python` one. Still seems to be on the System, that's weird but not the Core issue. 
My Question is: 
Can i set it so it uses `python3` instead of `python`?

**Comment by Kikobeats** [comment]
Hello, the library needs python3. These are the checks:

https://github.com/microlinkhq/youtube-dl-exec/blob/691291eb421c274427e0de85fe80c194210d04dc/scripts/preinstall.mjs#L14-L20

So make sure your system has python3 in a way the library can find and use it 🙂

**Comment by taynotfound** [comment]
Well. i have it installed. But just as python3 instead of python.
