### ISSUE TITLE
The requested module 'youtube-dl-exec' does not provide an export named 'youtubeDl'

### ISSUE THREAD

**Issue by Swimburger** [microlinkhq/youtube-dl-exec#198]
The typings provided alongside the module doesn't match the actual `index.js` contents.

I'm using this code:

```typescript
import { youtubeDl } from 'youtube-dl-exec'

const videoInfo = await youtubeDl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
  dumpSingleJson: true,
  preferFreeFormats: true,
  addHeader: ['referer:youtube.com', 'user-agent:googlebot'],
});
```

Which works from a types perspective, but doesn't actually work when running it using `tsx index.ts`.
I get this error:

```plaintext
The requested module 'youtube-dl-exec' does not provide an export named 'youtubeDl'
```

If I rewrite it to match the CommonJS counterpart, the code works, but the TypeScript typing doesn't.

```typescript
import youtubeDl from 'youtube-dl-exec'

const videoInfo = await youtubeDl('https://www.youtube.com/watch?v=6xKWiCMKKJg', {
  dumpSingleJson: true,
  preferFreeFormats: true,
  addHeader: ['referer:youtube.com', 'user-agent:googlebot'],
});
```

I'd be happy to update the index.js file in a PR to return the named `youtubeDl` export.

**Comment by Kikobeats** [comment]
Thanks for reporting. Can you modify the types file instead to match the expected export?
https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.d.ts
