### ISSUE TITLE
Error when installation

### ISSUE THREAD

**Issue by ItzFerr** [microlinkhq/youtube-dl-exec#202]
npm ERR! code 1
npm ERR! path C:\Desktop\project\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/postinstall.js
npm ERR! C:\Desktop\project\node_modules\youtube-dl-exec\scripts\postinstall.js:24
npm ERR!   let response = await fetch(url)
npm ERR!                  ^
npm ERR!
npm ERR! ReferenceError: fetch is not defined

**Comment by Kikobeats** [comment]
Hello,

You need to use Node v18 or higher
https://github.com/microlinkhq/youtube-dl-exec/blob/master/package.json#L154
