### ISSUE TITLE
 ERROR: [youtube] : Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by zNiGhTFuRyZNTT** [microlinkhq/youtube-dl-exec#208]
I was using yt-dlp binary in my app which is running into this error for a while, I thought your module might be using a different approach but its the same, how would you fix this error?

**Comment by Kikobeats** [comment]
Hello, this library is just a wrapper over [yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp)

I recommend to check the documentation there 🙂
