### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by simonegosetto** [microlinkhq/youtube-dl-exec#210]
i'm using this package with nestjs on back-end side:

`import youtubeDl, { Payload } from 'youtube-dl-exec';`

![image](https://github.com/user-attachments/assets/75e6ccc0-b0b3-4d9c-95fc-16fb9f1557a1)

the return of "youtubeDl" function is typed as Payload but the result is instead a string url

**Comment by Kikobeats** [comment]
I'm not following – this is the expected result:
https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.d.ts#L4

In which scenario the output is a string url?

**Comment by simonegosetto** [comment]
as you can see in screenshot if you pass options {format: 'best', getUrl: true} the result is a string

**Comment by Kikobeats** [comment]
Ops got it; can you make a PR updating the types? 🙏
https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.d.ts

**Comment by simonegosetto** [comment]
sure
