### ISSUE TITLE
Unable to use it in Nextjs 

### ISSUE THREAD

**Issue by pushkarsingh32** [microlinkhq/youtube-dl-exec#213]
Is this compatible with nextjs? Nodejs works fine but not in Nextjs

Thanks

**Comment by Kikobeats** [comment]
That's kind of expected, this command needs python installed in the machine:
https://github.com/microlinkhq/youtube-dl-exec/blob/master/scripts/preinstall.mjs

In any case with no information I can't debug nothing, sorry.

**Comment by Kikobeats** [comment]
If you use Next.js with SSR it should be works sinde it's running on server-side 🙂

Still not sure what you want to achieve, but alternatively you can use Microlink API:

https://api.microlink.io/?url=https://vimeo.com/868805980
