### ISSUE TITLE
Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by pushkarsingh32** [microlinkhq/youtube-dl-exec#214]
This is happening on hetzner server. 

passing cookie works for 2 min & again ask the same question. 

Any way to by pass this. 

`    const videoInfo = await retryOperation(() => youtubedl(url, {
            dumpSingleJson: true,
            cookies: './cookies.txt'
        }));`

**Comment by Kikobeats** [comment]
Try using `yt-dlp --help`, I guess you can pass cookies using `--add-headers`
