### ISSUE TITLE
Specifying directory.

### ISSUE THREAD

**Issue by jaysun0** [microlinkhq/youtube-dl-exec#216]
Can you please explain how to specify a directory for downloads?
In yt-dlp specification there is a separate flag for that: -P. Didn't find it in youtube-dl-exec.
I thought it could be done in 'outuput' (-o), but it seems to be just for file naming.

From yt-dlp docs:
"The -o option is used to indicate a template for the output file names while -P option is used to specify the path each type of file should be saved to."

**Comment by Kikobeats** [comment]
Sorry I can't help since it's a question related with yt-dlp flags, check the [documentation](https://github.com/yt-dlp/yt-dlp) 🙂
