### ISSUE TITLE
Merge audio and video

### ISSUE THREAD

**Issue by vietzz771** [microlinkhq/youtube-dl-exec#217]
I need to download a video from Vimeo, but currently, when I set 
{
allFormats = true
}
to merge into one file, but there is no sound. Can anyone help me?

**Comment by vietzz771** [comment]
I have tried many different methods, but it still doesn't work. {verbose: true} doesn't show any error information either.

**Comment by Kikobeats** [comment]
This is more related with yt-dlp itself; try to run `yt-dlp` standalone and find the right combination of parameters.

After that, do the same but using this library: running the CLI or using this package should be expect the same output under the same parameters.
