### ISSUE TITLE
Error: Sign in to confirm you’re not a bot - Missing flag "extractor-args"

### ISSUE THREAD

**Issue by NunoBento** [microlinkhq/youtube-dl-exec#221]
Well i know this package is a wrapper of yt-dlp. and it's not a problem here

However, yt-dlp have this [token tutorial](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#manually-acquiring-a-po-token-from-a-browser-for-use-when-logged-out) which i followed and it works. Using this i can download videos again.

On the readme of this `youtube-dl-exec` says it can take any yt-dlp flag, but i can't use the required one to bypass this problem `--extractor-args`.

How can i use this flag `--extractor-args` in this package?

**Comment by NunoBento** [comment]
i noticed there were no restictions about flags , which is cool. you just take them and use them in yt-dlp
so, i was able to bypass the error by using `any` and destructure. 

```ts
const extractorArgs: any = { extractorArgs: `youtube:player-client=web,default;po_token=web+${YT_PO_TOKEN}` };
const process = ytdl.exec(url, {
  cookies: 'cookies.txt',
  ...this.extractorArgs,
}
```

**Comment by Kikobeats** [comment]
That's great!

I'm going to close this since you adressed your own question; could be nice if play a bit with the code and made a PR for addint `extractorArgs` as part of types:

https://github.com/microlinkhq/youtube-dl-exec/blob/master/src/index.d.ts

wanna be a contributor? 👀

**Comment by PaulRBerg** [comment]
Using `any` is a bad practice. It would be helpful if `youtube-dl-exec` provided the types for `extractorArgs`!
