### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by 2813910154** [microlinkhq/youtube-dl-exec#222]
node version for v20.14.0;
<img width="657" alt="image" src="https://github.com/user-attachments/assets/9fc152fd-2cf0-4141-b90c-de2efc7892c6">
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/5ff8e346-efa8-4ec7-a8fb-d39dca2f131a">

i don't know why this happened

**Comment by Kikobeats** [comment]
Hello, you need to run in environment with Node.js
