### ISSUE TITLE
yt-dlp got updated

### ISSUE THREAD

**Issue by andrei10k** [microlinkhq/youtube-dl-exec#223]
The auto install of yt-dlp installs the older version, that appears to not work any more. i think it needs an update to the latest version released 3 days ago

**Comment by Kikobeats** [comment]
Hello,

This package doesn't hold a specific binary version; instead, a [postinstall](https://github.com/microlinkhq/youtube-dl-exec/blob/master/scripts/postinstall.js) script is run ever time it's installed to get the latest binary.

I checked it manually in mt computer and it works as usual.

**Comment by andrei10k** [comment]
hello. my already installed library stopped working on my app. i had to manually install the latest version of yt-dlp to have it working again
