### ISSUE TITLE
Error at parse node_modules\\youtube-dl-exec\\bin\\yt-dlp.exe

### ISSUE THREAD

**Issue by vrutikamoghariya23** [microlinkhq/youtube-dl-exec#225]
C:\Users\admin\Desktop\APP\Node Pactice\yt-download\node_modules\youtube-dl-exec\src\index.js:16
  throw Object.assign(new Error(stderr), { stderr, stdout }, details)
                      ^

Error
    at parse (C:\Users\admin\Desktop\Vrutika\Node Pactice\yt-download\node_modules\youtube-dl-exec\src\index.js:16:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  stderr: undefined,
  stdout: undefined,
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\admin\\Desktop\\Vrutika\\Node',
  path: 'C:\\Users\\admin\\Desktop\\Vrutika\\Node',
  spawnargs: [
    'Pactice\\yt-download\\node_modules\\youtube-dl-exec\\bin\\yt-dlp.exe',
    'https://www.youtube.com/shorts/zX2GKz3ahmA',
    '--dump-single-json',
    '--no-check-certificates',
    '--no-warnings',
    '--prefer-free-formats',
    '--add-header',
    'referer:youtube.com',
    '--add-header',
    'user-agent:googlebot'
  ]
}

Node.js v18.18.2

**Comment by vrutikamoghariya23** [comment]
Here is code
const youtubedl = require('youtube-dl-exec')

youtubedl('https://www.youtube.com/shorts/zX2GKz3ahmA', {
  dumpSingleJson: true,
  noCheckCertificates: true,
  noWarnings: true,
  preferFreeFormats: true,
  addHeader: ['referer:youtube.com', 'user-agent:googlebot']
}).then(output => console.log(output))

**Comment by Kikobeats** [comment]
It seems your system can't find Node.js, so it's related with your setup not with the library, sorry!
