### ISSUE TITLE
No file downloaded after deploying it on an ubuntu server (Again)

### ISSUE THREAD

**Issue by notmutiny** [microlinkhq/youtube-dl-exec#226]
Hello, this problem is extremely similar to this existing issue: https://github.com/microlinkhq/youtube-dl-exec/issues/220

In short, I have a docker container running Alpine Linux. The following are installed in the Dockerfile:

```dockerfile
RUN apk add --no-cache ffmpeg
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache yt-dlp
```

CMD is able to execute these commands fine:

```cmd
/usr/src/app # ffmpeg -version
ffmpeg version 6.1.2 [ ... ]

/usr/src/app # python --version
/usr/src/app # python3 --version
Python 3.12.8

/usr/src/app # yt-dlp --version
2024.12.23
```

But when downloading a link, nothing is downloaded and no logs are returned to print. 😞

I added `ENV DEBUG=youtube-dl-exec*` before `RUN npm install npm@latest` and verified `DEBUG=youtube-dl-exec*` is set using `printenv`. The solution `pip3 install -U yt-dlp` from the previous issue throws because `yt-dlp` is already installed.

I'm out of ideas debugging this problem because no logs are being returned by the library... I'm hoping I don't have to uninstall it and execute `yt-dlp` commands instead but that's the only thing I can think of since `yt-dlp` is working fine. Executing this youtube-dl-exec code on Windows runs fine. It's only the Linux container that fails without any logs.

Thank you for the help.

**Comment by Kikobeats** [comment]
Hello, 

It could be related with Docker and filesystem permissions.

Did you try to just execute `yt-dlp` to see if it generates a file? 

Closing since it's actually not related with the library, but continue updating the issue with any follow up information.

**Comment by notmutiny** [comment]
Thank you very much for the reply (especially around the holiday season). Yes, yt-dlp is able to generate a file as expected through the command line with the output in the expected directory. I can do everything as expected through CLI. It's just this library that is not creating a file or generating logs. If there's any way to make it generate a log of what is happening it would be very simple to resolve.

**Comment by notmutiny** [comment]
More debugging information -

`yt-dlp https://www.youtube.com/watch?v=tPEE9ZwTmy0` downloads the video and places at the root of my project, verifying file downloading works.

`yt-dlp https://www.youtube.com/watch?v=tPEE9ZwTmy0 -P /usr/src/app/temp/V1StGXR8_Z5jdHi6B-myT/` downloads the video and places in the output directory (typically generated by nanoid), verifying the permissions are okay (though I am new to Docker and it's possible Node.js has different permissions than me through CLI).

I'm downloading with these options:

```json
{
  "embedMetadata": true,
  "extractorArgs": "youtube:player_client=android,web",
  "noPlaylist": true,
  "output": "/usr/src/app/temp/bl6ooPMdedHmYTStwZcPp/Mylo the Cat - Shortest Video on Youtube [%(id)s] {T0000-T0001}.%(ext)s",
  "postprocessorArgs": "ffmpeg: -metadata album='Downloads' -metadata album_artist='Various Artists' -metadata artist='Mylo the Cat' -metadata comment='https://www.youtube.com/watch?v=tPEE9ZwTmy0' -metadata date='' -metadata genre='' -metadata title='Shortest Video on Youtube' -metadata track=''",
  "audioFormat": "opus",
  "audioQuality": 0,
  "extractAudio": true,
  "format": "bestaudio/best"
}
```

Using this function:

```js
console.log(await youtubedl(link, options));
```

Nothing happens during youtubedl() that I can observe. Is there a better way of getting log output from this library? I have debug logs enabled through my environment variable.

---

What's interesting is short commands like this are working fine, it's just downloading files that don't work.

```js
const youtubedlDescription = await youtubedl(linkWithoutParameters, {
  getDescription: true,
  skipDownload: true,
}).catch(e => { youtubedlErrorMessage = e.message });

const youtubedlFormats = await youtubedl(linkWithoutParameters, {
  listFormats: true,
  skipDownload: true,
}).catch(e => { youtubedlErrorMessage = e.message });

const youtubedlPayload = await youtubedl(linkWithoutParameters, {
  output: "%(duration>%H:%M:%S)s,%(id)s,%(view_count)s,%(like_count)s,%(upload_date)s, %(genre)s",
  print: "%(duration>%H:%M:%S)s,%(id)s,%(view_count)s,%(like_count)s,%(upload_date)s, %(genre)s",
  simulate: true,
  skipDownload: true
}).catch(e => { youtubedlErrorMessage = e.message });
```

---

Thank you again for the help and this library. Happy new year! 🎆

**Comment by notmutiny** [comment]
If it's helpful I am able to see this output:

```cmd
[youtube] HVStfWZsdBc: Downloading webpage
[youtube] HVStfWZsdBc: Downloading android player API JSON
```

Nothing else is printed before it throws. This is the result when it's working correctly in Windows outside of Docker:

```cmd
[youtube] Extracting URL: https://www.youtube.com/watch?v=HVStfWZsdBc
[youtube] HVStfWZsdBc: Downloading webpage
[youtube] HVStfWZsdBc: Downloading android player API JSON
[info] HVStfWZsdBc: Downloading 1 format(s): 251
[download] Destination: C:\app\temp\7ANp1CWuAHhnvaPdFciBx\Low Roar - Patience [HVStfWZsdBc] {T0000-T0545}.webm
[download] 100% of    5.90MiB in 00:00:03 at 1.79MiB/s
[ExtractAudio] Destination: C:\app\temp\7ANp1CWuAHhnvaPdFciBx\Low Roar - Patience [HVStfWZsdBc] {T0000-T0545}.opus
Deleting original file C:\app\temp\7ANp1CWuAHhnvaPdFciBx\Low Roar - Patience [HVStfWZsdBc] {T0000-T0545}.webm (pass -k to keep)
[Metadata] Adding metadata to "C:\app\temp\7ANp1CWuAHhnvaPdFciBx\Low Roar - Patience [HVStfWZsdBc] {T0000-T0545}.opus"
```

**Comment by notmutiny** [comment]
I fixed this problem after hours of troubleshooting. ✅ I converted my download options to their CLI equivalents and ran it using the provided binary.

```cli
/usr/src/app/node_modules/youtube-dl-exec/bin/yt-dlp https://www.youtube.com/watch?v=tPEE9ZwTmy0 --embed-metadata --extractor-args="youtube:player_client=android,web" --no-playlist --output="/usr/src/app/temp/V1StGXR8_Z5jdHi6B-myT/test.%(ext)s" --audio-format="mp3" --audio-quality=0 --extract-audio --format="bestaudio/best"
```

It resulted in this log and error:

```log
[youtube] Extracting URL: https://www.youtube.com/watch?v=tPEE9ZwTmy0
[youtube] tPEE9ZwTmy0: Downloading webpage
[youtube] tPEE9ZwTmy0: Downloading android player API JSON
WARNING: [youtube] tPEE9ZwTmy0: android client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=android+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
WARNING: [youtube] tPEE9ZwTmy0: web client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=web+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
WARNING: Only images are available for download. use --list-formats to see them
ERROR: [youtube] tPEE9ZwTmy0: Requested format is not available. Use --list-formats for a list of available formats
```

Removing the `extractorArgs` property from the download options fixed it (fixable with the PO Token too). I don't know why this error is thrown with the binary but not the library. I think the library should have thrown too. I also don't know why it throws in the Linux container and not the host Windows machine but that is an unrelated yt-dlp issue (version maybe?).

Anyways thanks for the help and I hope this information is helpful for someone else too. 👍

**Comment by Kikobeats** [comment]
@notmutiny thanks for reporting back; The logic for turning stdout/stderr into JavaScript erros was a bit flaked.

I solved that in the following commit https://github.com/microlinkhq/youtube-dl-exec/commit/5e8d2cd1f37f234403978eb304cb74589f93246f

Can you confirm `youtube-dl-exec@3.0.12` is now throwing the error?
