### ISSUE TITLE
erro youtube

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [microlinkhq/youtube-dl-exec#30]
[PLAY] → Obtive erros no comando /play → Command failed with exit code 3221225781: C:\Users\Meu\kaotic\node_modules\youtube-dl-exec\bin\youtube-dl.exe https://youtu.be/EiQmbrvvDaY --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer https://youtu.be/EiQmbrvvDaY -x --audio-format mp3 -o ./lib/media/audio/55759803244997.mp3 -

**Comment by Kikobeats** [comment]
I don't use windows, sorry, I can't debug
