### ISSUE TITLE
Usage in Electron with Webpack 5

### ISSUE THREAD

**Issue by y0x** [microlinkhq/youtube-dl-exec#31]
Did anyone got this package working in Electron using Webpack 5?

From what I know the thing which makes this complicated is that webpack 5 does not provide auto-polyfill anymore. Even after trying to add everything necessary I´m just running from one issue to another.

If someone has an idea which steps are needed to make this work, it would be great if you could share this :)

Thanks

**Comment by Kikobeats** [comment]
closing since it's more an electron related thing but will accept any PR for adding some clarification on the README 🙂
