### ISSUE TITLE
Download link directly to client 

### ISSUE THREAD

**Issue by matamune94** [microlinkhq/youtube-dl-exec#33]
Hi, i want to download the link directly to the client
In ytdl-core
I have code: 
```
app.get('/test', (req, res) => {
  var url = "https://www.youtube.com/watch?v=[id]";
  res.header("Content-Disposition", 'attachment; filename="Video.mp4');
  ytdl(url,{ format: 'mp4' }).pipe(res);
})
```

How can i do the same in youtube-dl-exec ? thanks for help

**Comment by Kikobeats** [comment]
Hello!

First, read https://github.com/ytdl-org/youtube-dl documentation to understand how CLI works.

Then, mimic the actions using this library 🙂

**Comment by matamune94** [comment]
> Xin chào!
> 
> Trước tiên, hãy đọc tài liệu https://github.com/ytdl-org/youtube-dl để hiểu cách hoạt động của CLI.
> 
> Sau đó, chỉ cần bắt chước hành động bằng thư viện này 🙂

I have read this library, but I still don't understand how to pass data to client, please give me a small example.
