### ISSUE TITLE
`youtube-dl` not being downloaded

### ISSUE THREAD

**Issue by EvasiveXkiller** [microlinkhq/youtube-dl-exec#34]
Just installed the dependency on a new project and realize that it did not work. 
Upon inspection inside of `.\node_modules\youtube-dl-exec\bin` is empty.
EDIT: I have installed this with no antivirus or malware software running, and it still did not install

The current workaround is just copying `youtube-dl` from another location to the `bin` folder.

Install details:
- Node v16.6.1
- npm 7.23.0
- Windows 10 21H1 Build 19043.1237

**Comment by Kikobeats** [comment]
That should be a Windows thing.

Can you check in your NPM logs if they are calling `scripts/postinstall` ?

**Comment by EvasiveXkiller** [comment]
It seems like everything is working fine now. Probably its just around that hour that it cant install. Thanks
