### ISSUE TITLE
Use node-fetch over got for postinstall?

### ISSUE THREAD

**Issue by Hazmi35** [microlinkhq/youtube-dl-exec#35]
node-fetch is smaller, and we don't need these request libraries other than downloading youtube-dl

**Comment by Kikobeats** [comment]
what's code size for `node-fetch`?

**Comment by Hazmi35** [comment]
> The main reason got is used is because it's one of the most used npm packages in the ecosystem and very actively maintained.
>
>So fortunately at least one of your dependencies is going to install got and the cost will be 0.

If it's by download usage `got` stills behind node-fetch, I love `got`, I used it too, but `node-fetch` is a better option IMO. 
Also `@mapbox/node-pre-gyp` now uses `node-fetch` instead of `needle`, plus I saw `youtube-dl-exec` usage increasing by `discord.js` bot developers where `discord.js` also uses `node-fetch`

> what's the code size for node-fetch? asking because bundlephobia can't report the size

npm's reporting 75.9 kB for v3, but GNU/du is reporting 136K, unfortunately, node-fetch v3 is now pure ESM, meaning it can't be imported from commonjs directly (this is probably why bundlephobia can't report its size, probably it didn't support ESM packages, yet).

For node-fetch v2 npm's reporting 149 kB and GNU/du is reporting 172K, and this is the bundlephobia results
![image](https://user-images.githubusercontent.com/32807631/134783436-30c0ef47-07ce-4c78-aeda-82a4d30c6316.png)

**Comment by Kikobeats** [comment]
Thanks for clarifying! 

Can you make a PR switching from got to `node-fetch@2`? 🙂

**Comment by Hazmi35** [comment]
> Thanks for clarifying!
> 
> Can you make a PR switching from got to `node-fetch@2`? I will be happy to merge it 🙂

Ah sorry for the late response, I can but seeing #38 is already opened, then we'll use that
