### ISSUE TITLE
Setting dumpJson: false throws an error 

### ISSUE THREAD

**Issue by wesbos** [microlinkhq/youtube-dl-exec#4]
throws:

youtube-dl: error: no such option: --no-dump-json

I realize I can just leave it off and it works, but if someone programatically sets it to false, it shoudn't prepend `--no-`

**Comment by Kikobeats** [comment]
I think that is expectable since `no-dump-json` is not a valid flag?

<img width="450" alt="Screen Shot 2021-03-04 at 23 10 35" src="https://user-images.githubusercontent.com/2096101/110037536-d5012b00-7d3e-11eb-9d66-000dd0ba0df3.png">
