### ISSUE TITLE
Handle different binary filename at runtime

### ISSUE THREAD

**Issue by Hazmi35** [microlinkhq/youtube-dl-exec#43]
### Why
I want to use yt-dlp with youtube-dl-exec. While using https://github.com/microlinkhq/youtube-dl-exec#environment-variables can download the correct binary, but on runtime, we need to set `YOUTUBE_DL_FILENAME` manually in `process.env`

### How
It should implement or document how to handle different binary filenames at runtime.

Either document how to do it with `process.env` or create something to handle these different binary filenames, either way, I'm fine

**Comment by Kikobeats** [comment]
Oh, gotcha.

What if we expose a constructor way, being the default `module.exports` bind to `YOUTUBE_DL_PATH` constant?

So users can continue using the library as usual and power users like you can take advantage of the constructor for creating different way to consume the binary.

**Comment by Hazmi35** [comment]
I agree with that

**Comment by 61soldiers** [comment]
My issue may somewhat be unrelated but can i change the path to the binary that yt-dl ultimately uses to download ?.
I have tried setting `YOUTUBE_DL_DIR` env variable to the desired path but `youtube-dl-exec` still tries to read the default path

The default path to the binary is inside `app.asar` and so it cannot read the binary. What i need it to point to is `/app,asar,unpacked`

### Environment
- Production build of electron using electron-builder

**Comment by Kikobeats** [comment]
`youtube-dl-exec@1.3.0` added binary customization:

```js
const { create: createYoutubeDl } = require('youtube-dl-exec')

const youtubedl = createYoutubeDl('/my/binary/path')
```

Also, added `YOUTUBE_DL_SKIP_DOWNLOAD` to avoid fetch youtube-dl remotely

```bash
YOUTUBE_DL_SKIP_DOWNLOAD=true npm install
```
