### ISSUE TITLE
Should we use npm_package_config over npm_config?

### ISSUE THREAD

**Issue by Hazmi35** [microlinkhq/youtube-dl-exec#44]
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#config

I think using `npm_package_config` is better over `npm_config`. why? `npm_config` env variables will always be lowercase when accessed from `process.env`, while `npm_package_config` does not.

It is also easier to read JSON files on runtime than `.npmrc` files (this could be used for #43)

Let me know if you agree or have other opinions about this

**Comment by Kikobeats** [comment]
My feeling is adding support for `.npmrc` is overcomplicating the thing.

Environment variables are more standard than NPM, in fact, npm is versioning so probably if you are using an old npm version (bundled by default with node) you probably can't take the benefit of this.

**Comment by Hazmi35** [comment]
Yes, I feel so too.

I don't think old npm is an issue here. From what I see `engines.node` is set to `>=12` and `npm_package_config` works on both npm v6 and v7. 
The problem is: I can't bother my user to set their environment variables just to setup hazmi35/jukebox, and setting using in a package.json seems a good idea, and I don't know if they even know what environment variable is 😅

I agree on dropping `.npmrc` support, but adding support for `npm_package_config` is very appreciated, I can create the PR, how about that?

**Comment by Kikobeats** [comment]
> The problem is: I can't bother my user to set their environment variables just to setup hazmi35/jukebox,

I'm checking your repo and looks like you are running at Heroku. Heroku allows setting environment variables. I'm missing something? why you can use it?

> I agree on dropping .npmrc support, but adding support for npm_package_config is very appreciated, I can create the PR, how about that?

Sure thing, can you do a PR doing both things? 🙂

**Comment by Hazmi35** [comment]
> I'm checking your repo and looks like you are running at Heroku. Heroku allows setting environment variables. I'm missing something? why you can use it?

Yes, I can create those environment variables on the app.json, but that will only apply to Heroku, for someone who hosts it on-premise they need to create those environment variables manually

**Comment by Hazmi35** [comment]
> Sure thing, can you do a PR doing both things? 🙂

Uh, I got into some problem here.
I forgot that `npm_package_config` would be overwritten with `youtube-dl-exec`'s package.json because ` node scripts/postinstall.js` is executed from `youtube-dl-exec` package.json scripts.

So because of this, we can't use `npm_package_config` here, I'm fine with .npmrc though, what do you think?

**Comment by Kikobeats** [comment]
That's great if you can update the documentation for reflecting that, It will be helpful for more users 🙂

**Comment by Hazmi35** [comment]
With #42 merged, I think we should close this issue
