### ISSUE TITLE
Hi Guys

### ISSUE THREAD

**Issue by 3vilcrow** [microlinkhq/youtube-dl-exec#51]
I have this error when install with npm im already have python installed python3

npm ERR! code 1
npm ERR! path /home/carlos/Documentos/Development/Projects/NextCloud projects/Node js Bot Nextcloud/node_modules/youtube-dl-exec
npm ERR! command failed
npm ERR! command sh -c npm run check && node scripts/postinstall.js
npm ERR! > youtube-dl-exec@1.3.2 check
npm ERR! > bin-version-check python ">=2"
npm ERR! Error: Couldn't find the `python` binary. Make sure it's installed and in your $PATH.

**Comment by boyphongsakorn** [comment]
i have a near same error as you

> youtube-dl-exec@1.3.2 postinstall D:\youtubegif\node_modules\youtube-dl-exec
> npm run check && node scripts/postinstall.js


> youtube-dl-exec@1.3.2 check D:\youtubegif\node_modules\youtube-dl-exec
> bin-version-check python ">=2"

Error: Couldn't find version of `python`
    at binaryVersion (file:///D:/youtubegif/node_modules/bin-version/index.js:55:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async binaryVersionCheck (file:///D:/youtubegif/node_modules/bin-version-check/index.js:14:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl-exec@1.3.2 check: `bin-version-check python ">=2"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl-exec@1.3.2 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\boy15\AppData\Roaming\npm-cache\_logs\2021-10-30T14_33_37_136Z-debug.log
npm WARN youtubegif@1.0.0 No description
npm WARN youtubegif@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl-exec@1.3.2 postinstall: `npm run check && node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl-exec@1.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\boy15\AppData\Roaming\npm-cache\_logs\2021-10-30T14_33_37_599Z-debug.log

how to fix that?

**Comment by 3vilcrow** [comment]
Same error, i think this is about of python version , in the path i dont have python, i have python3

**Comment by Kikobeats** [comment]
The binary `python` should be available.

**Comment by Tetheta** [comment]
I've verified that python works properly and is in the path. Tried both 2.7 and 3.8, I'm still getting this error.

**Comment by IshmamR** [comment]
Getting the same error, any solution?

**Comment by Kikobeats** [comment]
Hum strange; if you do this, what's the output for you?

```bash
$ python --version
Python 2.7.18

$npx bin-version-check-cli python ">=2"

$ echo $status
0
```

**Comment by tacohitbox** [comment]
@Kikobeats not the same person but i got this error
```
$ python --version
Python 2.7.18

$ npx bin-version-check-cli python ">=2"
npx: installed 91 in 4.289s
Unexpected identifier
```

**Comment by tacohitbox** [comment]
> @Kikobeats not the same person but i got this error
> 
> ```
> $ python --version
> Python 2.7.18
> 
> $ npx bin-version-check-cli python ">=2"
> npx: installed 91 in 4.289s
> Unexpected identifier
> ```

The issue was resolved with updating node. I was on some v10 version beforehand.

**Comment by jgorene** [comment]
I had the same problem on ubuntu 20.04. I solved it by installing this package... It saved me a lot of time... See on [stackoverflow](https://stackoverflow.com/questions/63517713/how-to-put-python-in-path-ubuntu-20-npm-install-fails)

`sudo apt install python-is-python3`
