### ISSUE TITLE
Can it play from a specific time?

### ISSUE THREAD

**Issue by osias10** [microlinkhq/youtube-dl-exec#53]
i want to stream youtube from a specific time 
so i add youtube url ?t=30 (likes 'https://www.youtube.com/watch?v=sqgxcCjD04s&t=149s')
but this plays the song from the beginning

`
const stream = ytdlexec(startUrl, {
    o: '-',
    q: '',
    f: 'bestaudio[ext=webm+acodec=opus+asr=48000]/bestaudio',
    r: '100K',
  }, { stdio: ['ignore', 'pipe', 'ignore'] })
`
this is my code

**Comment by Kikobeats** [comment]
I don't think so
