### ISSUE TITLE
YouTube links are throttled  

### ISSUE THREAD

**Issue by shaikh-amaan-fm** [microlinkhq/youtube-dl-exec#54]
The issue is similar to the one that [this pull request](https://github.com/fent/node-ytdl-core/pull/1022) in node-ytdl-core is fixing. Can someone do the same in youtube-dl-exec, please?

**Comment by Kikobeats** [comment]
Yes, you can do it 🙂

Although this library is oriented for generic purposes rather than downloading youtube videos, Happy to accept a PR that improve the experience
