### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by Qamar4P** [microlinkhq/youtube-dl-exec#55]
W20211109-17:05:13.651(5)? (STDERR) (node:19624) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
W20211109-17:05:13.697(5)? (STDERR)     at promisify (internal/util.js:209:11)
W20211109-17:05:13.697(5)? (STDERR)     at Object.<anonymous> (D:\irisvision\iv-web-management-platform\node_modules\youtube-dl-exec\node_modules\get-stream\index.js:7:35)
W20211109-17:05:13.697(5)? (STDERR)     at Module._compile (module.js:652:30)
W20211109-17:05:13.697(5)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20211109-17:05:13.698(5)? (STDERR)     at Module.load (module.js:565:32)
W20211109-17:05:13.698(5)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20211109-17:05:13.698(5)? (STDERR)     at Function.Module._load (module.js:497:3)
W20211109-17:05:13.698(5)? (STDERR)     at Module.require (module.js:596:17)
W20211109-17:05:13.698(5)? (STDERR)     at require (internal/module.js:11:18)
W20211109-17:05:13.698(5)? (STDERR)     at Object.<anonymous> (D:\irisvision\iv-web-management-platform\node_modules\youtube-dl-exec\node_modules\execa\lib\stream.js:3:19)
W20211109-17:05:13.698(5)? (STDERR)     at Module._compile (module.js:652:30)
W20211109-17:05:13.699(5)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20211109-17:05:13.700(5)? (STDERR)     at Module.load (module.js:565:32)
W20211109-17:05:13.700(5)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20211109-17:05:13.700(5)? (STDERR)     at Function.Module._load (module.js:497:3)
W20211109-17:05:13.700(5)? (STDERR)     at Module.require (module.js:596:17)
W20211109-17:05:13.700(5)? (STDERR) (node:19624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
W20211109-17:05:13.700(5)? (STDERR) (node:19624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kikobeats** [comment]
sorry but without a description about the issue I can't help

**Comment by Qamar4P** [comment]
@Kikobeats sorry, I add your library. Meteor build fails when running using node14.
