### ISSUE TITLE
QA issue: provide please, an example of ES style import

### ISSUE THREAD

**Issue by tst32** [microlinkhq/youtube-dl-exec#64]
Instead of provided  comonjs require i would like to use
```JavaScript 
import * as youtubedlexec from 'youtube-dl-exec'
const { create: createYoutubeDl } = youtubedlexec
const ytdlpath='path_to_my_ytdl'
const youtubedl = createYoutubeDl(ytdlpath)
```
then i use example code from readme

```

youtubedl('https://url-of-mine', {
  dumpSingleJson: true,
  noWarnings: true,
  noCallHome: true,
  noCheckCertificate: true,
  preferFreeFormats: true,
  youtubeSkipDashManifest: true,
  referer: 'https://example.com'
})
  .then(output => console.log(output))

```

and i got

in output this 
``` 
{
  id: '40011486',
  ext: 'mp3',
  url: 'http://s17sas.storage.yandex.net/get-mp3/...
skiped }
```
do i need to fetch url by my self, or youtube-dl-exec can do it? there is no problem but info question
how to do this?

**Comment by Kikobeats** [comment]
Since you are passing `dumpSingleJson`, the output is just info.

If you want to download the URL content, you should do it using your favorite fetch library 🙂

**Comment by tst32** [comment]
👍🏻 Thanks! And what is difference ``` dumpSingleJson``` and ``` dumpJson ```?

**Comment by Kikobeats** [comment]
good question, let me check

```
youtube-dl --help

    -j, --dump-json                      Simulate, quiet but print JSON information. See the "OUTPUT TEMPLATE" for a description of available keys.
    -J, --dump-single-json               Simulate, quiet but print JSON information for each command-line argument. If the URL refers to a playlist, dump the whole playlist information in
```

**Comment by tst32** [comment]
one more Q, please. Do i need parse output looking for filename, title etc, or i can access returning values? ``` output => console.log(`${output.filename})``` is undefined
