### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Alfagun74** [microlinkhq/youtube-dl-exec#7]
Similar to the older "youtube-dl" i need some types to use it.

**Comment by tibdev78** [comment]
same that @Alfagun74

**Comment by Kikobeats** [comment]
I'll accept a PR for this!

**Comment by Alfagun74** [comment]
@Kikobeats I'm sorry but i think you dont know how Git Issues Work. They are not bound to Bugs. An Issue can be anything from Questions to Bugs or Feature Requests. These types of requests need to stay open so people can see it and make a PR. Just leave it open until its done or close it, if you never want Typescript Support.
