### ISSUE TITLE
Expose currently configured binary path

### ISSUE THREAD

**Issue by JeffJassky** [microlinkhq/youtube-dl-exec#71]
I need a way to read the current binary path.

The only way I could find to do this was using `require('youtube-dl-exec/src/constants')` which works for now but doesn't seem ideal.

It may be useful to export the constants from the module itself. I have created a pull request containing this change.

Pull Request here: https://github.com/microlinkhq/youtube-dl-exec/pull/70

**Comment by Kikobeats** [comment]
Addressed at v2.0.4 🎉
