### ISSUE TITLE
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by UniqueElect** [microlinkhq/youtube-dl-exec#76]
I tried using your code from  **"Usage"** and got : **Uncaught ReferenceError: require is not defined.**
After that i tried a lot of fixes and changed  `const youtubedl = require('youtube-dl-exec')` to `import * as youtubedl from 'youtube-dl-exec';` and got another error : **Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)**
### webpack.config.js
```
module.exports = {
    entry: './src/js/2.js',
    optimization: {
        minimize: false
    },
    devtool: 'inline-source-map',
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    module: {
        rules: [
            {
                "test": /\.js$/,
                "exclude": /node_modules/,
                "use": {
                  "loader": "babel-loader",
                  "options": {
                    "presets": [
                      "@babel/preset-env",
                    ]
                  }
                }
              },
        ]
    },
    "mode": "none",
}

Package.json
{
 "scripts": {
  "start": "webpack --mode development --watch"
 },
 "dependencies": {
  "babel-loader": "^8.2.3",
  "path-browserify": "^1.0.1",
  "webpack": "^5.69.1",
  "webpack-cli": "^4.9.2",
  "youtube-dl-exec": "^2.0.5"
 },
  "type": "commonjs",
  
  "babel": {
    "presets": [
      "@babel/env"
  ]
}
}

**Comment by Kikobeats** [comment]
Sorry for that, but I can't help you too much, I'm not a webpack user.

The library was created to run under [Node.js](https://github.com/microlinkhq/youtube-dl-exec/blob/master/package.json#L57) context.

If you are using it in a browser context, You need to use it at backend side, or simply use [api.microlink.io](https://microlink.io/api) instead 🙂

e.g., https://api.microlink.io/?url=https://www.youtube.com/watch?v=6xKWiCMKKJg&audio
