### ISSUE TITLE
bin-version-check-cli Errors

### ISSUE THREAD

**Issue by SophieSnoww** [microlinkhq/youtube-dl-exec#78]
I've encountered two errors around `bin-version-check-cli`:

## Error 1

When running `npm i youtube-dl-exec`, I was met with the following error (on both Windows and Linux, though this example is from my windows machine):

```text
T:\all 3\code\search-and-download>npm i youtube-dl-exec
npm ERR! code 1
npm ERR! path T:\all 3\code\search-and-download\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! 'bin-version-check' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

I was able to solve this by manually running `npm i -g bin-version-check-cli`, but this could be listed as a dependency for `youtube-dl-exec`, which I think would solve this issue. (Though, I could be wrong)

## Error 2

Even after installing `bin-version-check-cli`, trying to run `npm i youtube-dl-exec` yields the following (again, on both OS's):

```text
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find the `python` binary. Make sure it's installed and in your $PATH.
```

However, I do have `python` installed, on both machines. The issue here arises because on both windows and linux, `python` wasn't a valid command. The valid command was `py` on windows and `python3` on linux. I was able to fix this on windows by installing python from the app store, which added the `python` command to the terminal. This seems fixable by looking for not just `python` but `py` and `python3`.

**Comment by Kikobeats** [comment]
Hello,

python should be available as expected in your system.

Consider to do something like this:
https://github.com/microlinkhq/youtube-dl-exec/issues/75#issuecomment-1043931976
