### ISSUE TITLE
consider switching to yt-dlp?

### ISSUE THREAD

**Issue by masterkain** [microlinkhq/youtube-dl-exec#85]
hello,
since the official youtube-dl release does not seems to be up to date I'm trying out the yt-dlp fork and so far it seems to work fine (and faster)

if someone is interested in testing those are the necessary ENVs:

```bash
YOUTUBE_DL_HOST=https://api.github.com/repos/yt-dlp/yt-dlp/releases?per_page=1
YOUTUBE_DL_FILENAME=yt-dlp
```

beside some different `output` behavior it works, so my suggestion is to consider an official switch -- if not feel free to close, thanks for the lib!

**Comment by Kikobeats** [comment]
I'm going to close because since it's possible to provide a different host, it isn't a real issue, and probably we are going to switch in any case soon

**Comment by Penlane** [comment]
Just another note: I supplied my own yt-dlp binary by using 
`YOUTUBE_DL_SKIP_DOWNLOAD` env variable together with `youtubedl.create(binaryPath)`.

Thanks for providing this option, so far it works without any issues 😀

**Comment by Kikobeats** [comment]
that's an excellent tip!

@masterkain @Penlane it will be really appreciated if you can make a quick PR for adding extra information about yt-dlp into the README, the rest of users will benefit of it 🙂

**Comment by optionsx** [comment]
> that's an excellent tip!
> 
> @masterkain @Penlane it will be really appreciated if you can make a quick PR for adding extra information about yt-dlp into the README, the rest of users will benefit of it 🙂

totally agree, switch to yt-dlp it's way more active also ton of extra features.
