### ISSUE TITLE
getting this error every time i try to install.

### ISSUE THREAD

**Issue by EdenTheBoa** [microlinkhq/youtube-dl-exec#86]
i keep getting this error every time i try to install, and yes i do have python.

npm ERR! code 1
npm ERR! path C:\Users\prote\OneDrive\Documents\GitHub\xxxx\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find version of `python`
npm ERR!     at binaryVersion (file:///C:/Users/prote/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users/prote/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prote\AppData\Local\npm-cache\_logs\2022-03-21T04_05_37_646Z-debug-0.log

**Comment by Kikobeats** [comment]
Hello,

Be sure `python` is available and version is 2 or higher.

Alternatively, if you want to skip this check, you can do `npm install --ignore-scripts`
