### ISSUE TITLE
"not a function" and "undefined" upon usage

### ISSUE THREAD

**Issue by PatricNox** [microlinkhq/youtube-dl-exec#88]
Hello!

Using the package like so, I seem to get the variable undefined.
```
 const youtubedl = require("youtube-dl-exec");
 const stream = youtubedl(
    data.queue[0].url,
    {
      o: '-',
      q: '',
      f: 'bestaudio[ext=webm+acodec=opus+asr=48000]/bestaudio',
      r: '100K',
    }, { stdio: ['ignore', 'pipe', 'ignore'] }
  )
  
  console.log(stream); // undefined
```

I've also tried to use the "raw" method, but that throws a "not a function".

```
 const youtubedl = require("youtube-dl-exec").raw;
 const stream = youtubedl( 
    data.queue[0].url,
    {
      o: '-',
      q: '',
      f: 'bestaudio[ext=webm+acodec=opus+asr=48000]/bestaudio',
      r: '100K',
    }, { stdio: ['ignore', 'pipe', 'ignore'] }
  )
  
  > "youtubedl" is not a function
```

My aim is to replace ytdl for my discord music bot with youtube-dl, using your wrapper.
Upon inspection, the package does indeed install a binary - im however very lost in why i cant use the package properly.

![image](https://user-images.githubusercontent.com/31646653/161535580-60a474f7-35ab-4828-8915-945e54377a8d.png)

Edit:` "youtube-dl-exec": "^2.0.9",`

**Comment by Kikobeats** [comment]
Hello,

I tried to reproduce, but it's working fine at my end.

It looks a specific problem related with Windows.

Can you run `npx envinfo --binaries --system` and paste the output?
