### ISSUE TITLE
Handling Readable Stream

### ISSUE THREAD

**Issue by wacns** [microlinkhq/youtube-dl-exec#97]
I'm working on a whatsapp bot using [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) which is about to download videos from social media. It requires me to send the media either using base64 string or a link.
Is there a way to do this without downloading the video on my desktop ?
I could do it with [node-ytdl-core](https://github.com/fent/node-ytdl-core) but it only allows youtube videos

**Comment by Kikobeats** [comment]
Hello,

Check the [.exec](https://github.com/microlinkhq/youtube-dl-exec#youtubedlexecurl-flags-options) method, it's a stream 🙂
